### PR TITLE
Special case for the `epel-release` yum-package

### LINKED ISSUE #70: Support epel-release on CentOS7
I need zeromq-devel, contained in `epel-release`, not the standard CentOS7 repository. I tried editing https://github.com/ocaml/opam-repository/blob/master/packages/conf-zmq/conf-zmq.0.1/opam like

```
opam-version: "1"
maintainer: "francois.berenger@inria.fr"
homepage: "http://zeromq.org/"
license: "LGPL"
build: [
  ["cc" "test.c" "-I/usr/local/include" "-L/usr/local/lib" "-lzmq"]
]
depexts: [
  [["debian"] ["libzmq3-dev"]]
  [["ubuntu"] ["libzmq3-dev"]]
  [["osx" "homebrew"] ["zeromq"]]
  [["alpine"] ["zeromq-dev"]]
  [["centos"] ["epel-release" "zeromq-devel"]]       # added epel-release
]
```

However, zeromq-devel cannot be installed because `epel-release` must be installed **before** zeromq-devel, i.e.,

```console
$ yum install epel-release zeromq-devel
```

says that zeromq-devel is not found, while

```console
$ yum install epel-release
$ yum install zeromq-devel
```

succeeds to install zeromq-devel.

I hope that depext supports such order-dependent installation. Some packages in https://github.com/ocaml/opam-repository require epel-release.

### PR DESCRIPTION
**Pull request by smondet**
Fixes #70, (cf. also #76).

Tested with [hdf5](https://github.com/ocaml/opam-repository/blob/master/packages/hdf5/hdf5.0.1.3/opam):

```
 $ docker run -it  ocaml/opam:centos-7_ocaml-4.03.0 bash
 $ opam pin add depext 'https://github.com/smondet/opam-depext.git#epel-release-special-case'
...
 $ opam depext --version
1.0.5+dev
 $ opam depext --yes hdf5
...
 $ opam installl --yes hdf5
...
```

### CODE REVIEW

**Comment by avsm** [comment]
I don't mind special-casing epel, but isn't this patch doing so unconditionally?  I was thinking that something like `centos:epel` as an additional tag might be appropriate, so that we can search for it in the list for the package and add the epel repository on demand.

**Comment by UnixJunkie** [comment]
nice hack

**Comment by smondet** [comment]
@avsm I did it like this because that's what seems to be already in use the
opam-repo. People specify the `epel-release` package when they need it (which
usually means that the `depext` error msg is good enough for CentOS interactive
users to fix it), like:

```
 [["centos"] ["epel-release" "hdf5-devel"]]
```

Cf. https://github.com/ocaml/opam-repository/search?utf8=%E2%9C%93&q=epel-release&type=

To pass CI builds, there is this *“run some script from the internet”* solution also:
https://github.com/ocaml/opam-repository/commit/24ae1fb14d066577449a77bfc10a84e7545506ad

```
  [["source" "centos"] ["https://gist.githubusercontent.com/akabe/9352e05d2413ccbefb2b52ea6ae81599/raw/7ad60a2be120849341cd7c5bf14656773cb7d405/centos-zmq.sh"]]
```

How do you think the depexp entry should look like?

```
 [["centos" "epel"] ["hdf5-devel"]]
```

or

```
 [["centos:epel"] ["hdf5-devel"]]
```

**Comment by UnixJunkie** [comment]
I personaly like the centos:epel one

**Comment by smondet** [comment]
@avsm any idea to move forward with this?
If you prefer any other definition than ``[["centos"] ["epel-release" "hdf5-devel"]]`` (the current one in the opam-repo), just say so :)

**Comment by AltGr** [comment]
I am not sure what to do with this with the current redifinition of depexts: https://github.com/ocaml/opam/pull/3074 , and especially the replacement for the "tags" here: https://github.com/ocaml/opam/issues/3058.

The patch as is would still actually work still, and may be the simplest solution!

**Comment by avsm** [comment]
This is ok by me; it just prioritises the epel package installation. A note in the README about how to specify the use of epel in centos depexts would be good. @altgr says he'll merge this in the latest release.

**Pull request merged**
