### PR TITLE
Support Amazon Linux

### PR DESCRIPTION
**Pull request by brendanlong**

### CODE REVIEW

**Comment by brendanlong** [comment]
Also a question: Is there any way to override `opam var os-distribution` until a new `opam-depext` release comes out with this fix?

**Comment by brendanlong** [comment]
Is there anything I need to do to get this merged? This is currently blocking us from upgrading to opam 2.0 on our build box, and opam 1.2 is going to stop working in less than a month :\

**Comment by rjbou** [comment]
Until this fix is merged and the new version is released, you can pin your version on your ci: `opam pin add opam-depext -k git https://github.com/arenadotio/opam-depext#amazon-linux`.

**Comment by rjbou** [comment]
>Also a question: Is there any way to override opam var os-distribution until a new opam-depext release comes out with this fix?

From the [manual](https://opam.ocaml.org/doc/Manual.html#Variables), you can override variables from configuration files. As `os-distribution` is a global variable, you can change the ` ~/.opam/config` file.

**Comment by rjbou** [comment]
I updated your PR, there was a conflict with a recently merged PR.

**Comment by brendanlong** [comment]
Cool, thanks

**Comment by rjbou** [comment]
Thanks!

**Pull request merged**
