### PR TITLE
fix package detection on Ubuntu and Debian

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
the Travis error is a joke, as always:
"E: Some index files failed to download. They have been ignored, or old ones used instead."

**Comment by samoht** [comment]
Can you send the output to `/dev/null`? This is very verbose.

**Comment by UnixJunkie** [comment]
I am testing a fix for the verbosity right now

**Comment by UnixJunkie** [comment]
it's completely silent now

**Comment by UnixJunkie** [comment]
Is there any problem with my proposal?

**Comment by UnixJunkie** [comment]
Will there be a new release soon?

**Comment by AltGr** [comment]
What was the problem ? This is a regression in terms of code (one request per packages instead of a single, global request)

**Comment by samoht** [comment]
Actually https://github.com/ocaml/opam-depext/commit/45bf7a85f6a4f33e8d8ab073328037721db83511 is **not** in 0.5. The current `opam pin add depext --dev` seems to work fine.

**Comment by UnixJunkie** [comment]
Well, the single global request was obviously broken.
On an Ubuntu or Debian, try

```
sudo aptitude install m4
opam depext lz4
```

If it tries or suggest to install m4, then it means the package detection is broken.

**Comment by samoht** [comment]
Seem to work fine with `master`:

```
$ opam pin
depext.0.5                git      https://github.com/ocaml/opam-depext.git
$ opam depext lz4
# Detecting depexts using flags: x86_64 linux ubuntu
# The following system packages are needed:
#  - liblz4-dev
#  - m4
# All required OS packages found.
```

**Comment by UnixJunkie** [comment]
Maybe there just need to be a new release of opam depext, that's possible.

**Comment by UnixJunkie** [comment]
I confirm the one in opam (depext 0.5) is broken for me.

**Comment by avsm** [comment]
tested on ubuntu and debian stable

**Comment by samoht** [comment]
@avsm there were already a fix in master

**Comment by samoht** [comment]
@AltGr commented that this PR will make detection slower (as it invokes one command for every package to test, instead of only one command for all the packages). Would be better to revert.

**Comment by AltGr** [comment]
Hm, yes, this is a regression, that can be accepted as a temporary workaround, but I'd still like to know what the bug was and fix it properly. The goal is to go the other way around (i.e. implement package checking in one command for as many OSes as possible). Once this is done, we may plan on better integration into OPAM.

**Comment by AltGr** [comment]
@UnixJunkie what's the output of `dpkg-query -W -f '${Package} ${Status}\n' liblz4-dev m4` on your distrib ?

**Comment by AltGr** [comment]
> I confirm the one in opam (depext 0.5) is broken for me.

The feature was implemented in 0.6 !

**Comment by UnixJunkie** [comment]
# dpkg-query -W -f '${Package} ${Status}\n' liblz4-dev m4

liblz4-dev install ok installed
m4 install ok installed

**Pull request merged**
