### PR TITLE
Extend the FILE protocol to relative paths

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Currently, it is not possible to execute source scripts without them being hosted somewhere on internet. This PR extends the FILE protocol (file://) to allow the user to give local scripts as its implementation by curl and wget doesn't support relative paths.

### CODE REVIEW

**Comment by avsm** [comment]
I'm just considering what to do with this. Now that we have sandboxing in opam2 and containers, I am inclined to remove the support for source installation entirely...

**Comment by kit-ty-kate** [comment]
That would be ok I suppose. I suppose it would be better to have something to say: "There is no package available for your system, try to install ```this```, ```this``` and ```that``` if you can" instead of the current ```# No extra OS packages requirements found.```.
But to be interesting it would need to a mandatory field if there is a ```depexts``` field I think.

**Comment by AltGr** [comment]
Thanks very much! The new design for depexts removes support for `source` dependency URLs, though (https://github.com/ocaml/opam/pull/3074) so this is unfortunately no longer relevant. Sorry about that and thanks for contributing!

**Comment by kit-ty-kate** [comment]
No problem. The new design looks nice !

**Pull request closed without merging**
