### PR TITLE
added support for Gentoo and Archlinux

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by AltGr** [comment]
Thanks! I prefer minimal patches without arrow alignment though ;)

**Comment by UnixJunkie** [comment]
It was aligned before, it is aligned after, I didn't change the style of the code

**Comment by AltGr** [comment]
Haha, fair enough, but it only got aligned by chance because all distributions were 6 letters :)

**Comment by UnixJunkie** [comment]
I see it was merged, thanks.

**Comment by AltGr** [comment]
Ah yes, sorry, forgot to close. Thank you!

**Pull request closed without merging**
