### PR TITLE
Check installed packages before installing

### PR DESCRIPTION
**Pull request by AltGr**
Please contribute the missing distributions! :)

This'll be very handy when we integrate into OPAM: we're getting closer
to having all the functionality needed (e.g., check system packages to
make sure they have not been removed).

### CODE REVIEW

**Comment by avsm** [comment]
Could a `depext -n` mode be added to just do the check and not the install? That would help in shell scripts.

**Comment by samoht** [comment]
Cool! We can also check the installed _opam_ packages to not have to call the solver at all!

**Comment by AltGr** [comment]
@samoht: just run without package argument

@avsm: good point, adding.

**Comment by samoht** [comment]
> just run without package argument

sorry I don't understand. what I mean is: if you do `opam depext foo` it would be nice to not call the solver if `foo` is already installed.

**Comment by AltGr** [comment]
@samoht: hm, that may still be useful to check that depexts for _already installed_ packages are met no ? (For example, I just spotted that caml-mode depends on emacs-nox on debian, which is wrong: should probably be just `emacs`, which is a metapackage depending on any  flavour). Besides, we still want to include dependencies of `foo` in the answer ?

Maybe I don't understand what you mean exactly.

Just added a `--dry-run` option (oops, misspelled in the commit. It's consistent with OPAM's). The usage you want is probably:

```
opam depext -n --no-source --short
```

which will silently return 0 if everything is fine, print a list of missing system packages and return 1 otherwise.

**A remark:** the checks in this PR don't handle source scripts (clearly, we can't check they have already run) -- we should really get rid of those. My idea is that converting them to opam packages would solve a lot of issues (upstream download management, signature, install once), would that be reasonably feasible ?

Also, due to the weird semantics, handling `source` flags consistently forces us to call opam and the solver _twice_...

**Comment by samoht** [comment]
My use-case is the mirage tool. `mirage configure` will call `opam depext <list of packages>` and `opam install <list of packages>` which might be slow on small arm boards. But yes, I think your new options could help.

**Comment by UnixJunkie** [comment]
I can try to add the support for
`Centos |`Fedora | `Mageia |`Archlinux | `Gentoo

**Comment by UnixJunkie** [comment]
I dit it in there: https://github.com/AltGr/opam-depext/pull/1

**Comment by AltGr** [comment]
@UnixJunkie thanks! Indeed, it's very nice to have support for detection, and we can improve and optimise on a per-distro basis afterwards.

**Pull request merged**
