### PR TITLE
Avoid to use failwith and propagate the exit code of the spawned commands

### PR DESCRIPTION
**Pull request by kit-ty-kate**
This should fix the issue we are having in mirage-ci (I can't test it right now however)

cc @avsm

### CODE REVIEW

**Comment by avsm** [comment]
I'm testing this on the live CI now

**Comment by kit-ty-kate** [comment]
It seems to be working well so far: https://ci.ocamllabs.io/ocaml/opam-repository/pr/11087?test=5%20V1.2%20All%20Distros

**Comment by avsm** [comment]
thanks!

**Comment by AltGr** [comment]
Curious why you needed the error code propagated ?

**Comment by kit-ty-kate** [comment]
```lines_of_command``` was used to call ```opam list ... --resolve=pkgs``` and this command fails when a package is not available. The CI needed this in order to know the difference between a real failure and the package being unavailable.

**Pull request merged**
