### PR TITLE
Treat opensuse-leap as opensuse in os-distribution

### LINKED ISSUE #109: Missing OpenSUSE 15 (leap) support
According to https://github.com/ocaml/opam-repository/pull/13077 OpenSUSE 15.0 has `opensuse-leap` as value for `os-distribution` and thus doesn't work well with opam packages that suppose `opensuse`

### PR DESCRIPTION
**Pull request by yutopp**
Resolve #109.

Outputs:
```bash
opam@4846b79c61c0:/opam> cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
opam@4846b79c61c0:/opam> ./opam-depext 
# Detecting depexts using flags: x86_64 linux opensuse
```

### CODE REVIEW

**Comment by yutopp** [comment]
Sorry, I think that it is not an issue of opam-depext.

**Comment by avsm** [comment]
Why is this not a opam-depext issue? The fix looks correct to me.

**Comment by AltGr** [comment]
OS detection is now done directly by opam, `opam-depext` being limited to choosing the proper package installation instructions.

**Comment by yutopp** [comment]
Thank you for your reply!

> OS detection is now done directly by opam

Yes, I realized that the published version of `opam-depext` on opam is based on `2.0` branch and there are no code base related to the patch in this PR. :sob: It uses `opam var os-distribution` which is a feature provided by `opam` to get an environment name, thus there is no function to determine the value of `os-distribution` now in `opam-depext`.

Thanks.

**Pull request closed without merging**
