### PR TITLE
add support for OracleLinux via the `ol` tag

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by hannesm** [comment]
imho `ol` is not self-explanatory (as are the other tags), I'd prefer it to be `oracle`..

**Comment by avsm** [comment]
ol is the tag they self identify with in their OS release, I guess we could make it more verbose

**Comment by avsm** [comment]
we pass through the OS-release tag right now though...

**Comment by hannesm** [comment]
i didn't know that... well, whatever you prefer... i was confused what `ol` means until now (but maybe this is only myself)

**Comment by avsm** [comment]
no not just you -- it's not a particularly good choice of os-release tag...

**Comment by hannesm** [comment]
then let's call it `oracle` pls :)

**Comment by avsm** [comment]
#46

**Pull request merged**
