### PR TITLE
update OpenBSD Support

### PR DESCRIPTION
**Pull request by adamsteen**
i have been working to port MirageOS to OpenBSD and i have update OpenBSD support in opam-depext.

- sudo_run_command
the OpenBSD way of `sudo`'ing is `doas`. also sudo is not install in base (and i don't have it or want it)

-  get_installed_packages
my ocam skills are non-existant so i had to guess this and would like some feedback, but to list the install packages with the path, the OpenBSD command is `pkg_info -mqP` which produces 
```
<SNIP>
devel/pkgconf
devel/quirks
devel/re2c
misc/redshift
x11/slock
<SNIP>
```
so i guessed the code from FreeBSD

Cheers
Adam

### CODE REVIEW

**Comment by mato** [comment]
ping @avsm @AltGr

**Comment by AltGr** [comment]
Looks good to me. Note that we provide the option to use `su` in the absence of `sudo`, does that exist on OpenBSD ?

**Comment by AltGr** [comment]
Thanks!

**Comment by adamsteen** [comment]
@AltGr 

OpenBSD does have su, but doas is much nicer, thanks for pushing this through

**Pull request merged**
