### PR TITLE
Add raspbian as a distro synonym for Debian

### PR DESCRIPTION
**Pull request by dsheets**
Prompted by @micksulley in ocaml/opam-repository#5880.

@micksulley, if you could confirm that this fixes the problem for you, that would be fantastic.

### CODE REVIEW

**Comment by micksulley** [comment]
What do I need to do to add raspbian?  I am very happy to make changes 
and test but have no idea what I need to do.
Thanks
Mick

**Comment by dsheets** [comment]
Hi @micksulley, I believe you'll need to do something like:

```
$ git clone https://github.com/dsheets/opam-depext.git
$ cd opam-depext
$ git checkout raspbian-distro
$ make
$ ./opam-depext -i ocamlfind
```

in order to test this change.

**Comment by micksulley** [comment]
This is what I get -

pi@raspberrypi:~/geneweb/opam-depext $ git checkout raspbian-distro
Branch raspbian-distro set up to track remote branch raspbian-distro 
from origin.
Switched to a new branch 'raspbian-distro'
pi@raspberrypi:~/geneweb/opam-depext $ make
ocamlbuild -tags annot,bin_annot,debug,use_unix -pkg cmdliner depext.native
/bin/sh: 1: ocamlfind: not found
Cannot run Ocamlfind.
Makefile:11: recipe for target '_build/depext.native' failed
make: **\* [_build/depext.native] Error 2

So it fails because it can't find ocamlfind but that was the reason I 
was trying to
install conf-m4.1

Any idea what to do next?

Thanks
Mick

**Comment by avsm** [comment]
try `opam pin add depext https://github.com/dsheets/opam-depext.git#raspbian-distro` instead

**Comment by micksulley** [comment]
I still get the same problem -

pi@raspberrypi:~/geneweb/opam-depext $ opam pin add depext 
https://github.com/dsheets/opam-depext.git#raspbian-distro
[NOTE] Package depext is already git-pinned to
        https://github.com/dsheets/opam-depext.git#raspbian-distro.
        This will erase any previous custom definition.
Proceed ? [Y/n] y

[depext] https://github.com/dsheets/opam-depext.git#raspbian-distro updated
[depext] Installing new package description from
https://github.com/dsheets/opam-depext.git#raspbian-distro

pi@raspberrypi:~/geneweb/opam-depext $ make
ocamlbuild -tags annot,bin_annot,debug,use_unix -pkg cmdliner depext.native
/bin/sh: 1: ocamlfind: not found
Cannot run Ocamlfind.
Makefile:11: recipe for target '_build/depext.native' failed
make: **\* [_build/depext.native] Error 2

**Comment by AltGr** [comment]
Thanks!

**Comment by micksulley** [comment]
Yes, it took a little while to figure it out because I didn't really 
know what I was doing, but yes it did fix the problem.

Thanks for your help.

**Comment by yallop** [comment]
Could we please have a new opam-depext release with this change?

**Comment by micksulley** [comment]
Hi,

Me and my family have had a great adventure recently, please read about it here <http://vonelagi.cleanslateprod.com/xystzuvc>

Yours, Mick Sulley

**Pull request merged**
